PREFIX : <http://cellosaurus.org/rdf#> 
PREFIX cvcl: <http://cellosaurus.org/cvcl/> 
PREFIX xref: <http://cellosaurus.org/xref/> 
PREFIX pub: <http://cellosaurus.org/pub/> 
PREFIX orga: <http://cellosaurus.org/orga/> 
PREFIX src: <http://cellosaurus.org/src/> 
PREFIX coll: <http://cellosaurus.org/coll/> 
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#> 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX skos: <http://www.w3.org/2004/02/skos/core#> 
PREFIX owl: <http://www.w3.org/2002/07/owl#> 
PREFIX foaf: <http://xmlns.com/foaf/0.1/> 

select (count(*) as ?misspelling_name_count) where { 

select ?cl ?n ?l (sum(?appears_somewhere) as ?appear_cnt) (sum(?has_note) as ?note_cnt)
where {
 ?cl a :CellLine.
 ?cl :misspellingName ?n.
?n a :CellLineName.
?n rdfs:label ?l.
optional {?n :appearsIn ?src. }
optional {?n rdfs:comment ?cm.}
bind(  if(bound(?src), 1, 0) as ?appears_somewhere)
bind(  if(bound(?cm), 1, 0) as ?has_note)
}
group by ?cl ?n ?l
}
