PREFIX : <http://cellosaurus.org/rdf/ontology#> 
PREFIX cvcl: <http://cellosaurus.org/rdf/cvcl/> 
PREFIX xref: <http://cellosaurus.org/rdf/xref/> 
PREFIX pub: <http://cellosaurus.org/rdf/pub/> 
PREFIX orga: <http://cellosaurus.org/rdf/orga/> 
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#> 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX skos: <http://www.w3.org/2004/02/skos/core#> 
PREFIX owl: <http://www.w3.org/2002/07/owl#> 
PREFIX foaf: <http://xmlns.com/foaf/0.1/> 
PREFIX dcterms: <http://purl.org/dc/terms/> 
PREFIX fabio: <http://purl.org/spar/fabio/> 
PREFIX up: <http://purl.uniprot.org/core/> 
PREFIX bibo: <http://purl.org/ontology/bibo/> 
PREFIX widoco: <https://w3id.org/widoco/vocab#> 
PREFIX vann: <http://purl.org/vocab/vann/> 

#select distinct (str(?ac) as ?ac) (str(?id) as ?cl_id) ('resistant to' as ?link) (str($label1) as ?compound_class) (str(?code2) as ?id) (str(?label2) as ?name) where {
select  ('resistant to' as ?link) (str($label1) as ?compound_class) (str(?code2) as ?id) (str(?label2) as ?name) (group_concat(distinct str(?ac) , ' ') as ?cl_acs) where {
  values ?label1 { "cyclic compound"^^xsd:string } .
   ?c1 skos:prefLabel ?label1 .
  # ?compound rdfs:label "Erlotinib"^^xsd:string .
 ?c1 skos:notation ?code1 .
?c2  :more_specific_than* ?c1 .
?c2 skos:notation ?code2 .
?c2 skos:prefLabel ?label2.
?cl :resistance / :xref ?c2.
?cl :accession ?ac .
#?cl :recommendedName / rdfs:label ?id.
}
group by  $label1?code2 ?label2

