PREFIX : <http://cellosaurus.org/rdf#> 
PREFIX cvcl: <http://cellosaurus.org/cvcl/> 
PREFIX xref: <http://cellosaurus.org/xref/> 
PREFIX pub: <http://cellosaurus.org/pub/> 
PREFIX orga: <http://cellosaurus.org/orga/> 
PREFIX src: <http://cellosaurus.org/src/> 
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#> 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX skos: <http://www.w3.org/2004/02/skos/core#> 
PREFIX owl: <http://www.w3.org/2002/07/owl#> 
PREFIX foaf: <http://xmlns.com/foaf/0.1/> 

select (sum(?cnt) as ?seqvar_details_count) where  {
select ?svc  ?zygo ?has_hgvs ?noneReported ?has_gene ?has_xref (count(distinct ?annot) as ?cnt) where {
  ?annot a :SequenceVariationComment .
  ?annot :sequenceVariation ?sv . ?sv a ?svc  .
  ?sv rdfs:label ?lbl .
  ?sv :noneReported ?noneReported .
  optional { ?sv rdfs:comment ?comment}
  optional { ?sv :zygosity ?zygo}
  optional { ?sv :hgvs ?hgvs}
  optional {?sv :gene ?gene}
  optional {?sv :reference ?xref}
  bind( if (bound(?gene), 1, 0) as ?has_gene)
  bind( if (bound(?comment), 1, 0) as ?has_comment)
  bind( if (bound(?hgvs), 1, 0) as ?has_hgvs)
  bind( if (bound(?xref), 1, 0) as ?has_xref)
}
group by ?svc ?zygo ?has_hgvs ?has_gene ?has_xref ?noneReported
order by ?svc  ?zygo ?has_hgvs ?has_gene ?has_xref ?noneReported
}
