PREFIX : <http://cellosaurus.org/rdf/ontology#> 
PREFIX cvcl: <http://cellosaurus.org/rdf/cvcl/> 
PREFIX xref: <http://cellosaurus.org/rdf/xref/> 
PREFIX pub: <http://cellosaurus.org/rdf/pub/> 
PREFIX orga: <http://cellosaurus.org/rdf/orga/> 
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#> 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX skos: <http://www.w3.org/2004/02/skos/core#> 
PREFIX owl: <http://www.w3.org/2002/07/owl#> 
PREFIX foaf: <http://xmlns.com/foaf/0.1/> 
PREFIX dcterms: <http://purl.org/dc/terms/> 
PREFIX fabio: <http://purl.org/spar/fabio/> 
PREFIX up: <http://purl.uniprot.org/core/> 
PREFIX bibo: <http://purl.org/ontology/bibo/> 
PREFIX widoco: <https://w3id.org/widoco/vocab#> 
PREFIX vann: <http://purl.org/vocab/vann/> 
select (count(*) as ?species_count) where { 
# select * where {
  ?cl a :CellLine .
  ?cl :fromIndividualBelongingToSpecies ?annot.
  ?annot a ?ctClass .
  ?annot rdfs:label ?label .
  ?annot :xref ?xref.
 }

