PREFIX : <http://localhost/rdf/ontology/> 
PREFIX cvcl: <http://localhost/rdf/cvcl/> 
PREFIX xref: <http://localhost/rdf/xref/> 
PREFIX pub: <http://localhost/rdf/pub/> 
PREFIX orga: <http://localhost/rdf/orga/> 
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#> 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX skos: <http://www.w3.org/2004/02/skos/core#> 
PREFIX owl: <http://www.w3.org/2002/07/owl#> 
PREFIX foaf: <http://xmlns.com/foaf/0.1/> 
PREFIX dcterms: <http://purl.org/dc/terms/> 
PREFIX fabio: <http://purl.org/spar/fabio/> 
PREFIX up: <http://purl.uniprot.org/core/> 
PREFIX bibo: <http://purl.org/ontology/bibo/> 
PREFIX widoco: <https://w3id.org/widoco/vocab#> 
PREFIX vann: <http://purl.org/vocab/vann/> 
PREFIX pubmed: <https://www.ncbi.nlm.nih.gov/pubmed/> 

select ?en (group_concat(?parent, ', ') as ?parents) where {
  ?en a owl:Class .
  ?en rdfs:isDefinedBy : .
  optional { ?en rdfs:subClassOf ?parent . }
}
group by ?en
order by ?en

