#
# Generated : 2023-05-10 11:16:12
#

from enum import Enum

class Fields(str, Enum):
	ID = "id"
	SY = "sy"
	IDSY = "idsy"
	AC = "ac"
	ACAS = "acas"
	DR = "dr"
	REF = "ref"
	RX = "rx"
	RA = "ra"
	RT = "rt"
	RL = "rl"
	WW = "ww"
	GENOME_ANCESTRY = "genome-ancestry"
	HLA = "hla"
	REGISTRATION = "registration"
	SEQUENCE_VARIATION = "sequence-variation"
	ANECDOTAL = "anecdotal"
	BIOTECHNOLOGY = "biotechnology"
	BREED = "breed"
	CAUTION = "caution"
	CHARACTERISTICS = "characteristics"
	METASTATIC_SITE = "metastatic-site"
	DONOR_INFO = "donor-info"
	SAMPLING_SITE = "sampling-site"
	DISCONTINUED = "discontinued"
	DOUBLING_TIME = "doubling-time"
	FROM = "from"
	GROUP = "group"
	KARYOTYPE = "karyotype"
	KNOCKOUT = "knockout"
	MSI = "msi"
	MISCELLANEOUS = "miscellaneous"
	MISSPELLING = "misspelling"
	MAB_ISOTYPE = "mab-isotype"
	MAB_TARGET = "mab-target"
	OMICS = "omics"
	PART_OF = "part-of"
	POPULATION = "population"
	PROBLEMATIC = "problematic"
	RESISTANCE = "resistance"
	SENESCENCE = "senescence"
	TRANSFECTED = "transfected"
	TRANSFORMANT = "transformant"
	VIROLOGY = "virology"
	CC = "cc"
	STR = "str"
	DI = "di"
	DIN = "din"
	DIO = "dio"
	OX = "ox"
	SX = "sx"
	AG = "ag"
	OI = "oi"
	HI = "hi"
	CH = "ch"
	CA = "ca"
	DT = "dt"
	DTC = "dtc"
	DTU = "dtu"
	DTV = "dtv"


